version: '3.8'
services:
  # fastapi service
  fastapi-app:
    image: mehran
    ports:
      - "80:80" 
    depends_on:
      - Mongodb

  # Mongodb Database service
  Mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: mehran-db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_HOST: mongodb://localhost
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
      - ./db_confs/mongod.conf:/etc/mongo/mongod.conf
    command: [ "mongod", "--config", "/etc/mongo/mongod.conf" ]
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: